RETRIEVE = "retrieve"
GENERATE = "generate"
WEB_SEARCH = "web_search"
INDEX_NAME = "langchain-doc-index-unstructured"
ENHANCED_QUERY_NODE = "enhanced_query_node"
RETRIEVE_AND_WEB_SEARCH = "retrieve_and_web_search"
