INDEX_NAME = "langchain-doc-index-unstructured"
MODEL_NAME = "gemini-1.5-flash"
SUMMARIZE_CONVERSATION_NODE = "summarize_conversation_node"
ENHANCED_QUERY_NODE = "enhanced_query_node"
RETRIEVE_NODE = "retrieve_node"
WEB_SEARCH_NODE = "web_search_node"
GENERATE_NODE = "generate_node"
